### ISSUE TITLE
Moving to the left is broken

### ISSUE THREAD

**Issue by NonlinearFruit** [tjunruh/Stratego#3]
- Player 2 can't move to the left
- Player 1 moves to the right when trying to move to the left

**Comment by tjunruh** [comment]
That is odd. The Windows version does not have that issue, but the Linux version does. I am going to spend some time to rework the program and see if I can integrate the Linux and Windows versions together into one set of files rather than having them separate as they are now. Hopefully, that will help to avoid these kinds of problems, and to make the code much nicer to work with.

**Comment by tjunruh** [comment]
This problem is fixed now. I rewrote the whole program with a better coding style. It should work with both Windows and Linux, but more testing is needed. I will continue adding some features such as rule customization and a few things with the display.

**Comment by NonlinearFruit** [comment]
Confirmed, left/right is working now for both players! UI is looking better as well 😁
